author: "Larry Li <lingyv.li@gmail.com>"
description: "New Dart runtime for ANTLR4."
homepage: "https://github.com/antlr/antlr4"
name: "antlr4"
version: "4.7.2"
license: "BSD-3-Clause"
dependencies: 
  logging:
  collection:
  uuid:
environment:
  sdk: ">=2.0.0 <3.0.0"
